#!/bin/bash

DMENU_LINES=15
UNICODE_DATA_URL=https://www.unicode.org/Public/UNIDATA/UnicodeData.txt
UNICODE_DATA_LOCAL_FILE=~/.local/share/UnicodeData.txt
EMOJI_DATA_LOCAL_FILE=~/.local/share/EmojiData.txt

if [ ! -f $EMOJI_DATA_LOCAL_FILE ]; then
    [ -f $UNICODE_DATA_LOCAL_FILE ] || \
        wget -c $UNICODE_DATA_URL -O $UNICODE_DATA_LOCAL_FILE

    codes=$(grep -i ^1f[3-9a-d][0-9a-f][0-9a-f] $UNICODE_DATA_LOCAL_FILE | \
        cut -d';' -f1)
    \echo -n > $EMOJI_DATA_LOCAL_FILE
    for code in $codes; do
        description=$(grep -i ^$code $UNICODE_DATA_LOCAL_FILE | \
            cut -d';' -f1,2 --output-delimiter=" " | tr [A-Z] [a-z])
        \echo -e "\U$code  = $description" >> $EMOJI_DATA_LOCAL_FILE
    done
fi

# 1f300 - 1f700

emoji=$(dmenu -p "Emoji:" -l $DMENU_LINES < $EMOJI_DATA_LOCAL_FILE | cut -f1 -d ' ')

if [ -n "$emoji" ]; then
    xdotool type $emoji
    #echo -n $emoji | xclip
    #notify-send "$emoji copied to primary clipboard"
    #echo -n $emoji | xclip -selection clipboard
    #notify-send "$emoji copied to clipboard"
fi

